#!/usr/bin/python

import os, sys
import subprocess
import objc_helper
import os_helper
import glob
from mod_pbxproj import XcodeProject
from subprocess import call

argv = sys.argv

if len(sys.argv) < 8:
  print "Not enough arguments to proceed. Exiting"
  sys.exit(0)

scriptName                  = sys.argv[0]
installPath                 = sys.argv[1]
player                      = sys.argv[2]
editorFolder                = os.path.split(scriptName)[0]
assetsFolder                = os.path.split(editorFolder)[0]
app_controller_helper_path  = os.path.join(installPath, "Libraries/AppControllerHelper.h")

if player == 'iPhone':
  
  #
  #   Copying Libraries
  #
  amplitudeLocation = os.path.join(assetsFolder, "Plugins/iOS/Amplitude")
  newAmplitudeLocation = os.path.join(installPath, "Classes")
  os_helper.copy(amplitudeLocation, newAmplitudeLocation)

  #
  #   Modifying the XCode project, messy!
  #
  pbxProjPath = os.path.join(installPath, "Unity-iPhone.xcodeproj/project.pbxproj")
  project = XcodeProject.Load(pbxProjPath)
  classes = project.get_or_create_group('Classes')
  amplitude = project.get_or_create_group('Amplitude', path='Amplitude', parent=classes, tree='<group>')
  for f in sorted(glob.glob(newAmplitudeLocation + '/Amplitude/*.[hm]')):
    project.add_file(os.path.basename(f), parent=amplitude, tree='<group>')

  project.add_file('System/Library/Frameworks/UIKit.framework', tree='SDKROOT')
  project.save()

  #
  #		Setting GCC Objective C exceptions to TRUE
  #
  objc_helper.set_flag(pbxProjPath, "GCC_ENABLE_OBJC_EXCEPTIONS", "YES")
